sudo: false
dist: trusty
language: python
cache: pip
python:
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script: nosetests --with-xcoverage --cover-package=paperbak
after_success:
  - coveralls
